### PR TITLE
Permit disabling use of http_proxy

### PR DESCRIPTION
**Pull request by bbockelm**
In the context of the HTCSS download plugin, it's not possible to remove the http_proxy environment variable.  Add a second environment variable to disable things.  Either of these are permitted:

- OSG_DISABLE_HTTP_PRXY
- OSDF_DISABLE_HTTP_PROXY

If the HTTP proxy is disabled, then fallback is also disabled.

Additionally, this permits it to accept OSDF_DISABLE_PROXY_FALLBACK as an alias to OSG_DISABLE_PROXY_FALLBACK.

### CODE REVIEW

**Comment by djw8605** [comment]
Has this been tested?

**Comment by bbockelm** [comment]
Yes - hand tested.  Easiest when you just set http_proxy to an invalid hostname and then look at the debug output.

**Comment by djw8605** [comment]
Looks good.  In the end, we will probably have to start using something like a configuration reader like [Viper](https://github.com/spf13/viper), but this will work for now.

**Review by djw8605 — APPROVED** [review]
LGTM

**Comment by DrDaveD** [comment]
I don't understand why this isn't disabled by default.  There's too many cases where squids will accidentally be used.

**Pull request merged**
